default_connection_name = "workflow"

[connections]
[connections.workflow]
account = "xazihzr-yfb07291"
user = "CPDEVRA7"
authenticator = "SNOWFLAKE_JWT"
warehouse = "COMPUTE_WH"
database = "CP_DEMO_DATABASE"
schema = "PUBLIC"
private_key_file = "rsa_key.p8"