name: Deploy data pipeline

# Action will run on pushes to selected branches
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
    SNOWFLAKE_DEFAULT_CONNECTION_NAME: "workflow"
    SNOWFLAKE_CONNECTIONS_WORKFLOW_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
    SNOWFLAKE_CONNECTIONS_WORKFLOW_USER: ${{ secrets.SNOWFLAKE_USER }}
    SNOWFLAKE_CONNECTIONS_WORKFLOW_PRIVATE_KEY_PASSPHRASE:
        ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSWORD }}
    SNOWFLAKE_CONNECTIONS_WORKFLOW_PRIVATE_KEY_RAW:
        ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
    GIT_REPO_DB: MY_GIT_REPOS
    GIT_REPO_SCHEMA: GITHUB
    GIT_REPO_NAME: snowflake_devops

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - uses: Snowflake-Labs/snowflake-cli-action@v1.5
              with:
                  cli-version: "latest"
                  default-config-file-path: "./.snowflake/config.toml"

            - name: Check Version and Verify Connection
              env:
                  PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSWORD }}
              run: |
                  snow --version
                  snow connection test --debug
                  echo "Using branch $GITHUB_REF_NAME"

            - name: Refresh Repo
              env:
                  PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSWORD }}
                  GIT_REPO_FQN:
                      ${{ env.GIT_REPO_DB }}.${{ env.GIT_REPO_SCHEMA }}.${{
                      env.GIT_REPO_NAME }}
              run: |
                  snow git fetch "$GIT_REPO_FQN"